styles.go
styles/ascii.json

This PR adds a default style that uses only ASCII characters. This is a good fallback style for situations where the terminal and/or localization might not be correctly configured.

Add ASCII default style

---

ansi/baseelement.go
ansi/blockelement.go
ansi/codeblock.go
ansi/context.go
ansi/heading.go
ansi/margin.go
ansi/paragraph.go
ansi/renderer.go
ansi/renderer_test.go
ansi/stylewriter.go
ansi/table.go
glamour.go

Users can override the desired profile by calling WithColorProfile.

Enforce TrueColor profile in tests

---

README.md
glamour.go
glamour_test.go
go.sum

This PR adds functions to pull user style configs from the user's terminal environment to prevent having to pass the style every time a program utilizing `glamour` is called (e.g. `glow -s ~/.dotfiles/glow/nord.json --pager README.md`).
I added in a "test" to make sure the custom renderer works. I can flesh out the tests more by generating a test Markdown file with embedded color information similar to existing tests if you'd like. I held off for now because I implemented the environment checking with minimal new code and it worked based on my local fiddling.
For context, this PR was originally discussed/designed [in this PR on the Glow project](https://github.com/charmbracelet/glow/pull/147).

GLAMOUR_STYLE environment variable support

---

README.md

This PR adds [GLab](https://github.com/profclems/glab) to the list of glamourous projects on the readme

Add GLab to the List of glamorous projects

---

ansi/renderer.go
go.mod
go.sum

https://github.com/yuin/goldmark/commit/9e0189df270cb443c204b51e89e2b0749b98370c broke backwards compatibility by renaming exported structs without a bump of the module's major version.
This commit updates glamour to use goldmark's new API.

Update for latest release of yuin/goldmark

---

ansi/elements.go
ansi/listitem.go
styles/examples/ordered_list.md
styles/examples/ordered_list.style
testdata/ordered_list.test

The problem is more thoroughly elaborated in [this issue](https://github.com/maaslalani/slides/issues/88) for a depending project.  The tl;dr is that most/all markdown processors will respect the first number in a numbered list, and ignore all subsequent values.  The commonmark reference implementation [implements this](https://spec.commonmark.org/dingus/?text=4.%20four%0A5.%20five%0A%0A), and github flavored markdown respects this as well.
This change is to recalculate the list enumeration value based on the starting number in the list.  It has been manually tested, and lists starting at 0 are rendered correctly as well.
Sample showing fixed behavior:
Sample showing fixed behavior with 0:

fix issue where lists that didn't start at 1 were not respected

---

go.mod
go.sum

Bump bluemonday to v1.0.16
Previous versions are susceptible to 2 vulnerabilities, v1.0.16 fixes them both.
CVE-2021-29272
moderate severity
Vulnerable versions: < 1.0.5
Patched version: 1.0.5
bluemonday before 1.0.5 allows XSS because certain Go lowercasing converts an uppercase Cyrillic character, defeating a protection mechanism against the "script" string.
CVE-2021-42576
moderate severity
Vulnerable versions: < 1.0.16
Patched version: 1.0.16
The bluemonday sanitizer before 1.0.16 for Go, and before 0.0.8 for Python (in pybluemonday), does not properly enforce policies associated with the SELECT, STYLE, and OPTION elements.

Bump bluemonday to v1.0.16

---

testdata/example.md

This PR fixes a small typo in the example document that's (mostly) about artichokes.

Fix a small typo in the artichoke example document

---

go.mod
go.sum

This tiny PR updates [`bluemonday`](https://github.com/microcosm-cc/bluemonday) from `v1.0.16` to `v1.0.17` to clear some irrelevant security warnings.

Bump bluemonday to v1.0.17

---

ansi/renderer_test.go

Allow each test to be a subtest, so users can run things like:
```sh
go test -v ./... -run 'TestRendererIssues/107'
```
In order to run a single issue test, which helps when trying to fix a
new one.

test: made each issue a subtest

---

ansi/elements.go
testdata/readme.markdown.in

per my understanding, bluemonday is already removing the comments, but we were appending an empty line to each html block, so each comment was actually being turned into an empty line instead of nothing.
per my tests, seems like we don't need to append that extra line... if we do, we can change it to only add if the contents are not empty.
closes #139

fix: do not replace comments with empty lines

---

go.mod
go.sum

The pinned [bluemonday](https://github.com/microcosm-cc/bluemonday) `v1.0.17` release has been [retracted](https://github.com/microcosm-cc/bluemonday/commit/c66f9ff141851967df87395b951cd166fab350b3); this PR bumps `bluemonday` to `v1.0.19`

Bump bluemonday to v1.0.19

---

ansi/codeblock.go

don't register chroma style if it's already registered
this could cause a "concurrent map writes" fatal error when used in a
concurrent setting like a bubbletea wish app

fix: register chroma style once

---

styles.go
styles/pink.json

Adds a `pink`/`purple` duotone theme for glamour.
I think the `code` style is a little less than ideal on light themes because it uses `0` which is very dark as a background.
Preview:
| Dark | Light |
| --- | --- |
| <img width="853" alt="image" src="https://user-images.githubusercontent.com/42545625/179052114-8ca34916-8470-4a7a-8634-7f31d5d3f74b.png"> | <img width="795" alt="image" src="https://user-images.githubusercontent.com/42545625/179052302-0e309cb2-36cd-4c1c-a332-ebe8d8deb785.png"> |

feat: Add `pink` theme

---

README.md
examples/custom_renderer/main.go

The default word wrap limit changed from 100 to 80 in commit 71e8425,
but this was un-documented other than a reference to the old 100 limit
in `examples/custom_renderer/main.go`
Remove the reference to the old 100 limit in the example file, and note
the new default of 80 in the readme where it's more likely to be noticed
(and corrected if the default ever changes again in the future).

Document default word wrap of 80 in readme

---

README.md

GitLab has adopted `glab` as its official CLI and moved the repo

Updating `glab` URL in Readme

---

glamour.go
glamour_test.go
styles.go
testdata/fuzz/fuzz.go

While building an application with Glamour rendering, the linter suggested adding constants when `"auto"` appeared in several places in the codebase. To that end, this PR introduces string constants that can be used to reference the default styles.
* `AsciiStyle`
* `AutoStyle`
* `DarkStyle`
* `DraculaStyle`
* `LightStyle`
* `NoTTYStyle`
* `PinkStyle`
Note that this revision uses the constants internally as well, however I have left the examples in the README as-is for sake of simplicity.

feat: use (exported) consts for default styles

---

ansi/elements.go
styles/examples/table.md
testdata/table.test

The `Text()` function does not work for the `AutoLink` struct.
Closes https://github.com/charmbracelet/glow/issues/525

Render URLs in table

---

ansi/heading.go
ansi/style.go
ansi/templatehelper.go
dracula.go
styles.go

- **fix(lint): cascadeStyles always passed true**
- **fix(lint): gomnd**

Fix lint issues

---

ansi/codeblock.go
ansi/renderer_test.go
glamour_test.go

fix: lint issues

---

glamour.go
glamour_test.go
styles/styles.go

This purify the Glamour API by removing the auto style feature and making the dark style the default. Glamour no longer needs to query the terminal background to determine the style to use. Querying the terminal is now part of Lip Gloss v2.

(v2) refactor: remove auto style and make dark the default

---

ansi/elements.go
ansi/table_links.go
ansi/testdata/TestRenderer/table_with_footer_auto_links_short.golden
internal/autolink/autolink.go
internal/autolink/autolink_test.go
styles/examples/table_with_footer_auto_links_short.md
styles/examples/table_with_footer_auto_links_short.style

- Closes https://github.com/charmbracelet/glamour/issues/413
- Follow-up of https://github.com/charmbracelet/glamour/pull/406
Some notes:
- We're prefixing `owner/repo` on every link, without trying to be smart in detecting whether that repo is the current one (always `owner/repo#123` instead of `#123`)
- We're only doing it for links inside tables for now, because only there we're showing a footer with the full link.
- Soon, when we [add support for OSC 8 hyperlinks](https://github.com/charmbracelet/glamour/pull/411), we can use this pattern everywhere and just add hyperlinks to the link preview (`repo/owner#123` would become clickable)
- Ideas for the future:
- Additionally to GitHub, we could support more sites like GitLab and other...
- We could expose something like …

feat(tables): format github links inside tables in a more readable manner

---

ansi/blockelement.go
ansi/codeblock.go
ansi/heading.go
ansi/margin.go
ansi/paragraph.go
ansi/table.go

*This is one of a series of changes related to https://github.com/charmbracelet/crush/issues/691*
------
As explained in https://github.com/charmbracelet/x/pull/518 this is performance critical for complex applications such as `crush`.
This change can be merged before the related change in `x`, but will not have any performance effect until the `x` PR is merged, and the package is updated here.
The `PenWriter` type internally uses `x/ansi.Parser` instances, which allocate large buffers. The corresponding change in `x` introduces a pool model for these parsers, making them reusable and reducing allocator/GC pressure **significantly** in complex applications like crush.
* https://github.com/charmbracelet/crush/issues/691

perf(ansi): ensure all PenWriter instances are closed
